---
# Version 3.7 for compose files corresponds with
# Docker engine 18.06.0 and newer (per Docker docs).
version: "3.7"

# Nested dictionary of containers to create. I'm demonstrating
# 3 CRM apps each exposing a different public TCP port. This is
# a "scale out" technique and you could put a load balancer in front.
services:
  web:
    build: "."
    image: "flask:latest"
    ports:
      - "5001:5000/tcp"

  db:
    image: "mysql:latest"
    command: "--default-authentication-plugin=mysql_native_password"
    environment:
      MYSQL_ROOT_PASSWORD: "faekpass123"
      MYSQL_DATABASE: "db"
...